version: '3.1'


# Define services
services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - db

  # Redis Service   
  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service    
    restart: unless-stopped
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - db

networks:
  backend:  
  db: